language: php

env:
  global:
    - MYSQL_DATABASE_NAME=oxid
    - MYSQL_USER=travis
  matrix:
    - OXID_VERSION=4.9.0
    - OXID_VERSION=4.9.6

php:
  - 5.3
  - 5.6

services:
  - mysql

before_install:
  - composer self-update

install:
  - scripts/download-oxid
  - composer install --no-interaction --prefer-dist

before_script:
  - scripts/prepare-oxid
  - scripts/link

script:
  - vendor/bin/phpunit
